---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: kafka-client
  name: super-user
  namespace: {{ .Release.Namespace }}
spec:
  authentication:
    type: scram-sha-512