# ---
# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: magicflow
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["*"]
# - apiGroups: ["*"]
#   resources: ["*"]
#   verbs: ["*"]

# ---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: magicflow
# subjects:
# - kind: ServiceAccount
#   name: magicflow
#   namespace: {{ .Release.Namespace }}
# roleRef:
#   kind: ClusterRole
#   name: magicflow
#   apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: magicflow
  namespace: {{ .Release.Namespace }}

