name: Build and Push MagicFlow Docker Image

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to push to GitHub Container Registry
      id-token: write  # Required for OIDC auth if using later

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker image name
        id: vars
        run: echo "IMAGE=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE . 

      - name: Push Docker image
        run: docker push $IMAGE
